export enum Types {
  number = 'integer',
  text = 'string',
  boolean = 'boolean',
  select = 'string_selectize',
  date = 'date',
  dateNow = 'date_now',
  handbookItem = 'handbook_item',
  afishaCity = 'afisha_city',
  afishaTag = 'afisha_tag',
  afishaEvent = 'afisha_event',
  cryptaSegments = 'crypta_segments',
  musicGenre = 'music_genre',
  musicGenreCode = 'music_genre_code',
  musicGenreId = 'music_genre_id',
  spam = 'spam',
  spamType = 'spam_type',
  double = 'double',
  gender = 'gender',
}
